spring.application.name=gestionUser
spring.mongodb.uri=mongodb://localhost:27017/gestionuser
spring.mongodb.database=gestionuser
server.port=9090
spring.cloud.config.enabled=false
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# CORS configuration for Angular
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,DELETE,PUT,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.max-age=3600
spring.web.cors.allow-credentials=true
# Désactiver tous les endpoints pour éviter le problème
management.endpoints.enabled-by-default=false
#management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.include=*
# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
#mail Sender
spring.mail.host=smtp.domain.com
spring.mail.port=****
spring.mail.username=your_address-mail@domain.com
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Désactive uniquement le mapping qui cause problème
#management.endpoints.enabled-by-default=false
#management.endpoints.web.exposure.include=health,info
# Expose explicitly tous les endpoints disponibles
#management.endpoints.web.exposure.include=*